<?php

/**
 * @file
 * Site Survey module file.
 */

/**
 * Implements hook_menu().
 */
function sitesurvey_menu() {
  $items['admin/reports/sitesurvey'] = array(
    'route_name' => 'sitesurvey_admin',
    'title' => 'Site Survey results',
    'description' => 'Collects the reports from site users.',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function sitesurvey_permission() {
  $permissions = array(
    'respond to site survey' => array(
      'title' => t('Respond to the Site Survey'),
    ),
    'view site survey results' => array(
      'title' => t('View Site Survey results'),
    ),
  );
  return $permissions;
}

/**
 * Saves a submission.
 */
function sitesurvey_save($record) {
  $record['submitted'] = REQUEST_TIME;
  $query = db_insert('sitesurvey')
    ->fields($record)
    ->execute();
}
