<?php

/**
 * @file
 * Site Survey module file.
 */

/**
 * Implements hook_permission().
 */
function sitesurvey_permission() {
  $permissions = array(
    'respond to site survey' => array(
      'title' => t('Respond to the Site Survey'),
    ),
    'view site survey results' => array(
      'title' => t('View Site Survey results'),
    ),
  );
  return $permissions;
}

/**
 * Saves a submission.
 */
function sitesurvey_save($values) {
  $query = db_insert('sitesurvey')
    ->fields($values)
    ->execute();
}
