base_field: id
base_table: sitesurvey
core: 8.x
description: ''
status: '1'
display:
  default:
    display_plugin: default
    id: default
    display_title: Master
    position: '1'
    display_options:
      access:
        type: perm
        options:
          perm: 'view site survey results'
      cache:
        type: none
        options: {  }
      query:
        type: views_query
        options:
          disable_sql_rewrite: '0'
          distinct: '0'
          slave: '0'
          query_comment: ''
          query_tags: {  }
      exposed_form:
        type: basic
        options:
          submit_button: Apply
          reset_button: '0'
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          expose_sort_order: '1'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        type: full
        options:
          items_per_page: '20'
          offset: '0'
          id: '0'
          total_pages: ''
          expose:
            items_per_page: '0'
            items_per_page_label: 'Items per page'
            items_per_page_options: '5, 10, 20, 40, 60'
            items_per_page_options_all: '0'
            items_per_page_options_all_label: '- All -'
            offset: '0'
            offset_label: Offset
          tags:
            previous: '‹ previous'
            next: 'next ›'
            first: '« first'
            last: 'last »'
          quantity: '9'
      style:
        type: table
        options:
          grouping: {  }
          row_class: ''
          default_row_class: '1'
          row_class_special: '1'
          override: '1'
          sticky: '0'
          caption: ''
          summary: ''
          description: ''
          columns:
            name: name
            hear: hear
            success: success
            recommend: recommend
            purpose: purpose
            improve: improve
            submitted: submitted
          info:
            name:
              sortable: '1'
              default_sort_order: asc
              align: ''
              separator: ''
              empty_column: '0'
              responsive: ''
            hear:
              sortable: '1'
              default_sort_order: asc
              align: ''
              separator: ''
              empty_column: '0'
              responsive: ''
            success:
              sortable: '1'
              default_sort_order: asc
              align: ''
              separator: ''
              empty_column: '0'
              responsive: ''
            recommend:
              sortable: '1'
              default_sort_order: asc
              align: ''
              separator: ''
              empty_column: '0'
              responsive: ''
            purpose:
              sortable: '1'
              default_sort_order: asc
              align: ''
              separator: ''
              empty_column: '0'
              responsive: ''
            improve:
              sortable: '1'
              default_sort_order: asc
              align: ''
              separator: ''
              empty_column: '0'
              responsive: ''
            submitted:
              sortable: '1'
              default_sort_order: asc
              align: ''
              separator: ''
              empty_column: '0'
              responsive: ''
          default: submitted
          empty_table: '0'
      row:
        type: fields
      fields:
        name:
          table: sitesurvey
          field: name
          id: name
          relationship: none
          group_type: group
          admin_label: ''
          label: Name
          exclude: '0'
          alter:
            alter_text: '0'
            text: ''
            make_link: '0'
            path: ''
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '1'
            ellipsis: '1'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '1'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
        hear:
          id: hear
          table: sitesurvey
          field: hear
          relationship: none
          group_type: group
          admin_label: ''
          label: Hear
          exclude: '0'
          alter:
            alter_text: '0'
            text: ''
            make_link: '0'
            path: ''
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '1'
            ellipsis: '1'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '1'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
          plugin_id: standard
          provider: views
        success:
          id: success
          table: sitesurvey
          field: success
          relationship: none
          group_type: group
          admin_label: ''
          label: Success
          exclude: '0'
          alter:
            alter_text: '0'
            text: ''
            make_link: '0'
            path: ''
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '1'
            ellipsis: '1'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '1'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
          type: yes-no
          type_custom_true: ''
          type_custom_false: ''
          not: '0'
          plugin_id: boolean
          provider: views
        recommend:
          id: recommend
          table: sitesurvey
          field: recommend
          relationship: none
          group_type: group
          admin_label: ''
          label: Recommend
          exclude: '0'
          alter:
            alter_text: '0'
            text: ''
            make_link: '0'
            path: ''
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '1'
            ellipsis: '1'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '1'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
          type: yes-no
          type_custom_true: ''
          type_custom_false: ''
          not: '0'
          plugin_id: boolean
          provider: views
        purpose:
          id: purpose
          table: sitesurvey
          field: purpose
          relationship: none
          group_type: group
          admin_label: ''
          label: Purpose
          exclude: '0'
          alter:
            alter_text: '0'
            text: ''
            make_link: '0'
            path: ''
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '1'
            ellipsis: '1'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '1'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
          plugin_id: standard
          provider: views
        improve:
          id: improve
          table: sitesurvey
          field: improve
          relationship: none
          group_type: group
          admin_label: ''
          label: Improve
          exclude: '0'
          alter:
            alter_text: '0'
            text: ''
            make_link: '0'
            path: ''
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '1'
            ellipsis: '1'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '1'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
          plugin_id: standard
          provider: views
        submitted:
          id: submitted
          table: sitesurvey
          field: submitted
          relationship: none
          group_type: group
          admin_label: ''
          label: Submitted
          exclude: '0'
          alter:
            alter_text: '0'
            text: ''
            make_link: '0'
            path: ''
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '1'
            ellipsis: '1'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '1'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
          date_format: html_date
          custom_date_format: ''
          timezone: ''
          plugin_id: date
          provider: views
      filters: {  }
      sorts: {  }
      title: 'Site Surveys'
      header: {  }
      footer: {  }
      empty:
        area:
          id: area
          table: views
          field: area
          relationship: none
          group_type: group
          admin_label: ''
          empty: '1'
          tokenize: '0'
          content: "<p>There are no survey results.</p>\n"
          format: basic_html
          plugin_id: text
          provider: views
      relationships: {  }
      arguments: {  }
  page_1:
    display_plugin: page
    id: page_1
    display_title: Page
    position: '1'
    display_options:
      path: admin/reports/sitesurvey
      menu:
        type: normal
        title: 'Site Surveys'
        description: 'Site survey results'
        name: admin
        weight: '0'
        context: '0'
label: 'Survey results'
module: views
id: sitesurvey
tag: ''
langcode: en
